# Generated by Django 5.2 on 2025-04-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='trade_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='trade_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
