# Generated by Django 5.2 on 2025-04-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tradehistory_trade_ref_id_tradehistory_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokeapi_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
